runtime: go111

handlers:
  - url: /(.*\.(css|gif|png|jpg|ico|js|html))
    static_files: dist/\1
    upload: dist/(.*\.(css|gif|png|jpg|ico|js|html))
  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
