/**
 * server API
 * サンプルアプリのREST API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Media } from './media';
import { Tag } from './tag';
import { User } from './user';


/**
 * 記事
 */
export interface Article { 
    /**
     * 記事ID
     */
    readonly id?: string;
    /**
     * 記事タイトル
     */
    title?: string;
    /**
     * ユーザー
     */
    user?:User;
    /**
     * コンテンツ
     */
    content?: string;
    /**
     * アップロード日
     */
    createDate?: string;

        /**
     * アップロード日
     */
    uploadDate?: string;

    author?: string;
    media?: Media;
    tags?: Array<Tag>;
}
