/**
 * server API
 * サンプルアプリのREST API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Media { 
    /**
     * イメージ
     */
    readonly id?: string;
    /**
     * ファイル名
     */
    name?: string;
    /**
     * 画像URL
     */
    readonly url?: string;
    /**
     * メディアタイプ
     */
    type?: Media.TypeEnum;

    /**
     * アップロード日
     */
    uploadDate?: string;
}
export namespace Media {
    export type TypeEnum = 'image/png' | 'image/jpg' | 'image/jpeg' | 'image/gif';
    export const TypeEnum = {
        Png: 'image/png' as TypeEnum,
        Jpg: 'image/jpg' as TypeEnum,
        Jpeg: 'image/jpeg' as TypeEnum,
        Gif: 'image/gif' as TypeEnum
    };
}
