version: 2
jobs:
  client_test:
    docker:
      - image: circleci/node:10.9.0-browsers
    working_directory: /home/circleci/projects/github.com/sample-app
    steps:
      - checkout
      - run:
          name: run unit test
          command: ./bin/test_client.sh
  
  # deploy_app:
  #   docker:
  #     - image: google/cloud-sdk:latest
  #   working_directory: /go/src/go-sample-circleci
  #   steps: 
  #     - checkout 
  #     - run: apt-get update && apt-get install -y sudo
  #     - run:
  #        name: Permission denied回避
  #        command: sudo chmod +x ./bin/deploy.sh
  #     - run:
  #         name: activate service account
  #         command: |
  #           echo ${GCP_KEY_FILE} > /key.json
  #           gcloud auth activate-service-account --key-file /key.json
  #     - run:
  #         name: deploy to app engine
  #         command: ./bin/deploy.sh ${PROJECT_ID}
workflows:
  version: 2
  test-and-deploy:
   jobs:
    - client_test
#         - deploy_app:
#             requires:
#               - test
#             filters:
#              branches:
#                 only:
#                   - master