// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Articles 記事リスト
// swagger:model Articles
type Articles struct {

	// articles
	Articles []*Article `json:"articles"`
}

// Validate validates this articles
func (m *Articles) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArticles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Articles) validateArticles(formats strfmt.Registry) error {

	if swag.IsZero(m.Articles) { // not required
		return nil
	}

	for i := 0; i < len(m.Articles); i++ {
		if swag.IsZero(m.Articles[i]) { // not required
			continue
		}

		if m.Articles[i] != nil {
			if err := m.Articles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("articles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Articles) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Articles) UnmarshalBinary(b []byte) error {
	var res Articles
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
