// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ErrorResponse error response
// swagger:model ErrorResponse
type ErrorResponse struct {

	// エラーコード
	// Enum: [not_found unauthorized_request invalid_request internal_server_error conflict_resource]
	Error string `json:"error,omitempty"`

	// エラー詳細内容
	ErrorDetail string `json:"error_detail,omitempty"`
}

// Validate validates this error response
func (m *ErrorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var errorResponseTypeErrorPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["not_found","unauthorized_request","invalid_request","internal_server_error","conflict_resource"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		errorResponseTypeErrorPropEnum = append(errorResponseTypeErrorPropEnum, v)
	}
}

const (

	// ErrorResponseErrorNotFound captures enum value "not_found"
	ErrorResponseErrorNotFound string = "not_found"

	// ErrorResponseErrorUnauthorizedRequest captures enum value "unauthorized_request"
	ErrorResponseErrorUnauthorizedRequest string = "unauthorized_request"

	// ErrorResponseErrorInvalidRequest captures enum value "invalid_request"
	ErrorResponseErrorInvalidRequest string = "invalid_request"

	// ErrorResponseErrorInternalServerError captures enum value "internal_server_error"
	ErrorResponseErrorInternalServerError string = "internal_server_error"

	// ErrorResponseErrorConflictResource captures enum value "conflict_resource"
	ErrorResponseErrorConflictResource string = "conflict_resource"
)

// prop value enum
func (m *ErrorResponse) validateErrorEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, errorResponseTypeErrorPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ErrorResponse) validateError(formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	// value enum
	if err := m.validateErrorEnum("error", "body", m.Error); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorResponse) UnmarshalBinary(b []byte) error {
	var res ErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
